import type { Metadata } from 'next';
import { type JSX } from 'react';

import { geistMono, geistSans } from '@/app/fonts';
import { Providers } from '@/components/providers';

import '@/app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html className={`${geistSans.variable} ${geistMono.variable}`} lang="en">
      <body className="antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
