services:
  postgres_next_app:
    image: postgres:alpine
    container_name: postgres_next_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next_app
    volumes:
      - postgres_next_app_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - next_app

  redis_next_app:
    image: redis:alpine
    container_name: redis_next_app
    volumes:
      - redis_next_app_data:/data
    ports:
      - '6379:6379'
    networks:
      - next_app

networks:
  next_app:

volumes:
  postgres_next_app_data:
  redis_next_app_data:
